"""Initial Migration

Revision ID: 962c5f409ff8
Revises: 8ea21792e88c
Create Date: 2022-05-16 00:50:22.467622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962c5f409ff8'
down_revision = '8ea21792e88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'date_created')
    # ### end Alembic commands ###
